apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: kube-system
  name: node-custom-setup-lvm
  labels:
    k8s-app: node-custom-setup
spec:
  selector:
    matchLabels:
      k8s-app: node-custom-setup
  template:
    metadata:
      labels:
        k8s-app: node-custom-setup
    spec:
      hostNetwork: true
      hostPID: true
      initContainers:
        - name: init-node
          command:
            - nsenter
            - --mount=/proc/1/ns/mnt
            - --
            - sh
            - -c
          args:
            - mknod -m 660 /dev/loop11  b 7 11;
              apt update && apt install -y lvm2;
              truncate -s 5G /host/tmp/lvm.hdd;
              losetup /dev/loop11 /host/tmp/lvm.hdd;
              sed -i 's/udev_sync = 1/udev_sync = 0/g' /etc/lvm/lvm.conf;
              sed -i 's/udev_rules = 1/udev_rules = 0/g' /etc/lvm/lvm.conf
          image: debian
          securityContext:
            privileged: true
      containers:
        - name: wait
          image: debian:latest
          imagePullPolicy: Always
          command:
            - sleep
            - infinity
  updateStrategy:
    type: RollingUpdate
